- name: Determine Python major version
  set_fact:
    python_major_version: "{{ python_version.split('.')[0] }}"
    python_major_minor_version: "{{ python_version.split('.')[0] }}.{{ python_version.split('.')[1] }}"
  when: python_version is defined

- name: Install Python Required Development Tools
  yum:
    name:
      - zlib-devel
      - bzip2-devel
      - libffi-devel
      - wget
      - ncurses-devel
      - sqlite-devel
      - readline-devel
      - tk-devel
    state: present
    update_cache: yes
  when: python_version is defined and python_version != ""
  retries: 3
  delay: 5

- name: Install Python from source
  shell: |
    wget -q https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz && \
    tar xf Python-{{ python_version }}.tgz && \
    cd Python-{{ python_version }}  && \
    ./configure && \
    make --quiet -j8 && \
    make --quiet altinstall -j8 && \
    cd .. && \
    rm -rf Python-{{ python_version }} && \
    rm Python-{{ python_version }}.tgz && \
    rm -rf /usr/bin/python*
  when: python_version is defined and python_version != ""
  retries: 3
  delay: 5

- name: Create symlink for python
  raw: ln -s /usr/local/bin/python{{ python_major_minor_version }} /usr/bin/python
  when: python_version is defined and python_version != ""

- name: Create symlink for python to python{{ python_major_version }}
  raw: ln -s /usr/local/bin/python{{ python_major_minor_version }} /usr/bin/python{{ python_major_version }}
  when: python_version is defined and python_version != "" and python_major_version != "2"

- name: Install Pip3
  raw: wget -q https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py && rm get-pip.py && ln -s /usr/local/bin/pip3 /usr/bin/pip
  when: python_version is defined and python_version != "" and python_major_version == "3"

- name: Install Pip
  raw:
    wget https://files.pythonhosted.org/packages/b2/40/4e00501c204b457f10fe410da0c97537214b2265247bc9a5bc6edd55b9e4/setuptools-44.1.1.zip  && \
    unzip setuptools-44.1.1.zip  && \
    cd setuptools-44.1.1  && \
    python setup.py install  && \
    cd .. && \
    rm -rf setuptools-44.1.1.zip setuptools-44.1.1  && \
    wget https://files.pythonhosted.org/packages/53/7f/55721ad0501a9076dbc354cc8c63ffc2d6f1ef360f49ad0fbcce19d68538/pip-20.3.4.tar.gz  && \
    tar -xvf pip-20.3.4.tar.gz  && \
    cd pip-20.3.4  && \
    python setup.py install  && \
    cd .. && \
    rm -rf pip-20.3.4.tar.gz pip-20.3.4  && \
    pip -V
  when: python_version is defined and python_version != "" and python_major_version == "2"

- name: Validate Python installation
  raw: python --version
  when: python_version is defined and python_version != ""