- name: Install Java
  apt:
    name: openjdk-{{ java_version }}-jdk
    state: present
  when: java_version is defined and java_version != ""
  retries: 3
  delay: 5
- name: Install Maven
  shell: |
    cd /opt && wget https://archive.apache.org/dist/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz &&  \
    tar -xvf apache-maven-{{ maven_version }}-bin.tar.gz &&  \
    rm -rf apache-maven-{{ maven_version }}-bin.tar.gz && \
    rm -rf /opt/java-{{ jdk_11_version_dir }} /opt/sonar-scanner-{{ sonar_scanner_version }}
  when: java_version is defined and java_version != ""
  retries: 3
  delay: 5

