- name: Install Podman
  apt:
    name: podman
    state: present
  when: install_podman is defined and install_podman | bool
- name: Remove docker if it exists
  shell: |
    rm -rf /usr/bin/docker &&
    rm -rf /usr/local/bin/docker
    ln -s /usr/bin/podman /usr/bin/docker
  when: install_podman is defined and install_podman | bool
  retries: 3
  delay: 5

- name: Validate podman installation
  shell: |
    podman --version
    docker --version
    ls /bin | grep docker
  when: install_podman is defined and install_podman | bool