- name: Determine Python major version
  set_fact:
    python_major_version: "{{ python_version.split('.')[0] }}"
    python_major_minor_version: "{{ python_version.split('.')[0] }}.{{ python_version.split('.')[1] }}"
  when: python_version is defined

- name: Install Python Required Development Tools
  apt:
    name:
      - zlib1g-dev
      - bzip2
      - libffi-dev
      - wget
      - libncurses5-dev
      - libsqlite3-dev
      - libreadline-dev
      - tk-dev
    state: present
    update_cache: yes
  when: python_version is defined and python_version != ""
  retries: 3
  delay: 5

- name: Install Python from source
  shell: |
    wget -q https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz && \
    tar xf Python-{{ python_version }}.tgz && \
    cd Python-{{ python_version }}  && \
    ./configure && \
    make --quiet && \
    make --quiet altinstall && \
    cd .. && \
    rm -rf Python-{{ python_version }} && \
    rm Python-{{ python_version }}.tgz && \
    rm -rf /usr/bin/python*
  when: python_version is defined and python_version != ""
  retries: 3
  delay: 5

- name: Create symlink for python
  raw: ln -s /usr/local/bin/python{{ python_major_minor_version }} /usr/bin/python
  when: python_version is defined and python_version != ""

- name: Create symlink for python to python{{ python_major_version }}
  raw: ln -s /usr/local/bin/python{{ python_major_minor_version }} /usr/bin/python{{ python_major_version }}
  when: python_version is defined and python_version != "" and python_major_version != "2"

- name: Install Pip3
  raw: wget -q https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py && rm get-pip.py && ln -s /usr/local/bin/pip3 /usr/bin/pip
  when: python_version is defined and python_version != "" and python_major_version == "3"
  retries: 3
  delay: 5

- name: Validate Python installation
  raw: python --version
  when: python_version is defined and python_version != ""