- name: Install Python
  apt:
    name:
      - zlib1g-dev
      - bzip2
      - libffi-dev
      - wget
      - libncurses5-dev
      - libsqlite3-dev
      - libreadline-dev
      - tk-dev
    state: present
    update_cache: yes
  when: python_version is defined and python_version != ""
  retries: 3
  delay: 5
- name: Install Python
  shell: |
    wget https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz && \
    tar xvf Python-{{ python_version }}.tgz && \
    cd Python-{{ python_version }}  && \
    ./configure && \
    make clean && \
    make -j 8 && \
    make install && \
    rm -rf /usr/local/bin/python && \
    mv /usr/local/bin/${PYTHON_VERSION} /usr/local/bin/python
    cd .. && \
    rm -rf Python-{{ python_version }} && \
    rm Python-{{ python_version }}.tgz && \
    python --version
  when: python_version is defined and python_version != ""
  retries: 3
  delay: 5
- name: Install Python PIP
  apt:
    name: python3-pip
    state: present
  when: python_version is defined and python_version != ""
  retries: 3
  delay: 5
