Master:
  StatefulSet:
    Enabled: false
    Replicas: 1
    # StatefulSetUpdateStrategy must be 'RollingUpdate' or 'OnDelete'
    UpdateStrategy: RollingUpdate
    # Name of the Kubernetes scheduler to use
    SchedulerName: ""
  Name: jenkins-master
  Image: "amamba-io/jenkins"
  ImageTag: "${VERSION}-2.502"

Agent:
  Image: "amamba-io/inbound-agent"
  ImageTag: jdk21
  Builder:
    Base:
      Image: amamba-io/jenkins-agent-base
      Tag: ${VERSION}
    NodeJs16:
      Image: amamba-io/jenkins-agent-nodejs
      Tag: ${VERSION}
    Maven:
      Image: amamba-io/jenkins-agent-maven
      Tag: ${VERSION}-jdk1.8
    Mavenjdk11:
      Image: amamba-io/jenkins-agent-maven
      Tag: ${VERSION}-jdk11
    Golang:
      Image: amamba-io/jenkins-agent-go
      Tag: ${VERSION}
    Python:
      Image: amamba-io/jenkins-agent-python
      Tag: ${VERSION}
    ContainerRuntime: docker # Available values: docker, podman