- name: Remove System Docker
  shell: |
    rm -rf /usr/local/bin/docker* &&  
    rm -rf /usr/bin/docker*
  when: required is defined and required | bool
- name: Install Docker
  shell: |
    curl -L -o docker-{{ docker_version }}.tgz https://download.docker.com/linux/static/stable/{{ arch_x86_64 or arch_aarch64 }}/docker-{{ docker_version }}.tgz &&  
    tar xzvf docker-{{ docker_version }}.tgz &&  
    mv docker/* /usr/local/bin/ &&  
    rm -rf docker-{{ docker_version }}.tgz &&  
    docker --version
  register: docker_install_result
  until: docker_install_result is succeeded
  when: required is defined and required | bool
  retries: 3
  delay: 5

- name: Install Helm
  shell: |
    curl -f https://get.helm.sh/helm-v{{ helm_version }}-linux-{{ arch_amd64 or arch_arm64 }}.tar.gz | tar xzv -C /usr/local/bin && mv /usr/local/bin/linux-{{ arch_amd64 or arch_arm64 }}/helm /usr/local/bin/helm && helm version
  register: helm_install_result
  until: helm_install_result is succeeded
  when: required is defined and required | bool
  retries: 3
  delay: 5

- name: Install Helm Plugins
  shell: |
    helm plugin install https://github.com/chartmuseum/helm-push.git &&  
    helm cm-push --help
  when: required is defined and required | bool

- name: Install Kubectl
  shell: |
    curl -f -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/{{ arch_amd64 or arch_arm64 }}/kubectl &&  
    chmod +x kubectl &&  
    mv kubectl /usr/local/bin/
  when: required is defined and required | bool
  retries: 3
  delay: 5

- name: Install Argo Rollouts CLI
  shell: |
    curl -LO https://github.com/argoproj/argo-rollouts/releases/download/{{ argo_rollouts_cli_version }}/kubectl-argo-rollouts-linux-{{ arch_amd64 or arch_arm64 }} &&  
    chmod +x ./kubectl-argo-rollouts-linux-{{ arch_amd64 or arch_arm64 }} &&  
    mv ./kubectl-argo-rollouts-linux-{{ arch_amd64 or arch_arm64 }} /usr/local/bin/kubectl-argo-rollouts
  when: required is defined and required | bool
  retries: 3
  delay: 5

- name: Install yq
  shell: |
    wget https://github.com/mikefarah/yq/releases/download/{{ yq_version }}/yq_linux_{{ arch_amd64 or arch_arm64 }} -O /usr/local/bin/yq &&  
    chmod +x /usr/local/bin/yq
  when: required is defined and required | bool
  retries: 3
  delay: 5

- name: Install Kustomize
  shell: |
    curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash &&  
    mv kustomize /usr/local/bin/
  when: required is defined and required | bool
  retries: 3
  delay: 5

- name: Install Java 11
  shell: |
    curl -fLo jdk-{{ jdk_11_version }}.tar.gz https://aka.ms/download-jdk/microsoft-jdk-{{ jdk_11_version }}-linux-{{ arch_x64 or arch_aarch64 }}.tar.gz &&  
    tar zxf jdk-{{ jdk_11_version }}.tar.gz &&  
    mv jdk-{{ jdk_11_version_dir }}+9 /opt/java-{{ jdk_11_version_dir }} &&  
    rm jdk-{{ jdk_11_version }}.tar.gz
  when: required is defined and required | bool
  retries: 3
  delay: 5
- name: Install sonar scanner
  shell: |
    curl -Lo /tmp/sonar_scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-{{ sonar_scanner_version }}.zip &&  
    unzip /tmp/sonar_scanner.zip -d /opt/ &&  
    mv /opt/sonar-scanner-{{ sonar_scanner_version }} /opt/sonar-scanner &&  
    sed -i '1 a JAVA_HOME=/opt/java-{{ jdk_11_version_dir }}' /opt/sonar-scanner/bin/sonar-scanner &&  
    echo 'export PATH=/opt/sonar-scanner/bin:$PATH' >> /etc/profile.d/sonar-scanner.sh &&  
    sonar-scanner --version
  when: required is defined and required | bool
  retries: 3
  delay: 5

- name: Install Go
  shell: |
    wget https://golang.google.cn/dl/go{{ go_version }}.linux-{{ arch_amd64 or arch_arm64 }}.tar.gz  
    tar -xvf go{{ go_version }}.linux-{{ arch_amd64 or arch_arm64 }}.tar.gz  
    rm -rf go{{ go_version }}.linux-{{ arch_amd64 or arch_arm64 }}.tar.gz  
    mv go /usr/local/go  
    go version
  when: go_version is defined and go_version != ""
  retries: 3
  delay: 5

- name: Install ArgoCD Cli
  shell: |
    curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/{{ argocd_cli_version }}/argocd-linux-{{ arch_amd64 or arch_arm64 }}  
    chmod +x /usr/local/bin/argocd
  when: required is defined and required | bool
  retries: 3
  delay: 5