name: Build Images
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+

  workflow_dispatch:
  
jobs:
  init-variable:
    runs-on: ubuntu-latest
    outputs:
      container_tag: ${{ steps.init_variable.outputs.container_tag }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: output environment variable
        id: init_variable
        run: |
          set -x
          if [[ $GITHUB_REF =~ ^refs/tags/v ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(git describe --tags --abbrev=8)
          fi
          echo "container_tag=${VERSION}" >> $GITHUB_OUTPUT

  manifest-conformance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Validate Helm Policy
        run: |
          OUTPUT=github make conftest 

  build-jenkins:
    permissions:
      contents: read
      packages: write
    needs: [init-variable, manifest-conformance]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: use-setup-buildx-action
        uses: docker/setup-buildx-action@v2
      - name: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build jenkins
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./
          file: ./Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/jenkins:${{ needs.init-variable.outputs.container_tag }}-2.413
            ${{ secrets.DOCKER_USERNAME }}/jenkins:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-jenkins-agent-base:
    permissions:
      contents: read
      packages: write
    needs: [init-variable, manifest-conformance]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: use setup-buildx-action
        uses: docker/setup-buildx-action@v2
      - name: build jenkins agent with docker
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: ./jenkins-agent/base/Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/jenkins-agent-base:${{ needs.init-variable.outputs.container_tag }}
            ${{ secrets.DOCKER_USERNAME }}/jenkins-agent-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: build jenkins agent with podman
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: ./jenkins-agent/base/podman/Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/jenkins-agent-base:${{ needs.init-variable.outputs.container_tag }}-podman
            ${{ secrets.DOCKER_USERNAME }}/jenkins-agent-base:latest-podman
          build-args: |
            REGISTRY_REPO=${{ secrets.DOCKER_USERNAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-agent-nodejs:
    needs: [build-jenkins-agent-base, init-variable]
    strategy:
      matrix:
        runtime: [docker, podman]
        version: ["16.17.0", "18.20.4", "20.16.0"]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: init variables
        id: step-variable
        run: |
          export "runtime=$([ ${{ matrix.runtime }} == podman ] && (echo -podman))"
          echo "runtime=${runtime}" >> $GITHUB_OUTPUT
          export "nodejsVersion=$( echo -${{ matrix.version }})"
          echo "suffix=${nodejsVersion}${runtime}" >> $GITHUB_OUTPUT
      - name: use setup-buildx-action
        uses: docker/setup-buildx-action@v2
      - name: build jenkins agent with nodejs
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./jenkins-agent/nodejs
          file: ./jenkins-agent/nodejs/Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/jenkins-agent-nodejs:${{ needs.init-variable.outputs.container_tag }}${{ steps.step-variable.outputs.suffix }}
            ${{ secrets.DOCKER_USERNAME }}/jenkins-agent-nodejs:latest${{ steps.step-variable.outputs.suffix }}
          build-args: |
            REGISTRY_REPO=${{ secrets.DOCKER_USERNAME }}
            RUNTIME=${{ steps.step-variable.outputs.runtime }}
            VERSION=${{ matrix.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-agent-python:
    needs: [build-jenkins-agent-base, init-variable]
    strategy:
      matrix:
        runtime: [ docker, podman ]
        version: [ "2.7.9", "3.8.19", "3.10.9", "3.11.9" ]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: init variables
        id: step-variable
        run: |
          export "runtime=$([ ${{ matrix.runtime }} == podman ] && (echo -podman))"
          echo "runtime=${runtime}" >> $GITHUB_OUTPUT
          export "pythonVersion=$( echo -${{ matrix.version }})"
          echo "suffix=${pythonVersion}${runtime}" >> $GITHUB_OUTPUT
      - name: use setup-buildx-action
        uses: docker/setup-buildx-action@v2
      - name: build jenkins agent with python
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./jenkins-agent/python
          file: ./jenkins-agent/python/Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/jenkins-agent-python:${{ needs.init-variable.outputs.container_tag }}${{ steps.step-variable.outputs.suffix }}
            ${{ secrets.DOCKER_USERNAME }}/jenkins-agent-python:latest${{ steps.step-variable.outputs.suffix }}
          build-args: |
            REGISTRY_REPO=${{ secrets.DOCKER_USERNAME }}
            RUNTIME=${{ steps.step-variable.outputs.runtime }}
            VERSION=${{ matrix.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-agent-go:
    needs: [ build-jenkins-agent-base, init-variable ]
    strategy:
      matrix:
        runtime: [ docker, podman ]
        version: [ "1.17.13", "1.18.10", "1.20.14", "1.22.6"]
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: Login to ghcr.io
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: init variables
          id: step-variable
          run: |
            export "runtime=$([ ${{ matrix.runtime }} == podman ] && (echo -podman))"
            echo "runtime=${runtime}" >> $GITHUB_OUTPUT
            export "goVersion=$( echo -${{ matrix.version }})"
            echo "suffix=${goVersion}${runtime}" >> $GITHUB_OUTPUT
        - name: use setup-buildx-action
          uses: docker/setup-buildx-action@v2
        - name: build jenkins agent with go
          uses: docker/build-push-action@v4.1.1
          with:
            context: ./jenkins-agent/go
            file: ./jenkins-agent/go/Dockerfile
            github-token: ${{ secrets.GITHUB_TOKEN }}
            push: true
            provenance: false
            platforms: linux/amd64,linux/arm64
            tags: |
              ${{ secrets.DOCKER_USERNAME }}/jenkins-agent-go:${{ needs.init-variable.outputs.container_tag }}${{ steps.step-variable.outputs.suffix }}
              ${{ secrets.DOCKER_USERNAME }}/jenkins-agent-go:latest${{ steps.step-variable.outputs.suffix }}
            build-args: |
              REGISTRY_REPO=${{ secrets.DOCKER_USERNAME }}
              RUNTIME=${{ steps.step-variable.outputs.runtime }}
              VERSION=${{ matrix.version }}
            cache-from: type=gha
            cache-to: type=gha,mode=max

  build-agent-maven:
    needs: [ build-jenkins-agent-base, init-variable ]
    strategy:
      matrix:
        runtime: [docker, podman]
        version: [8, 11, 17, 21]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: init variables
        id: step-variable
        run: |
          export "runtime=$([ ${{ matrix.runtime }} == podman ] && (echo -podman))"
          export "jdkVersion=$( echo -jdk${{ matrix.version }})"
          echo "runtime=${runtime}" >> $GITHUB_OUTPUT
          echo "suffix=${jdkVersion}${runtime}" >> $GITHUB_OUTPUT
      - name: use setup-buildx-action
        uses: docker/setup-buildx-action@v2
      - name: build jenkins agent with maven
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./jenkins-agent/maven
          file: ./jenkins-agent/maven/Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/jenkins-agent-maven:${{ needs.init-variable.outputs.container_tag }}${{ steps.step-variable.outputs.suffix }}
            ${{ secrets.DOCKER_USERNAME }}/jenkins-agent-maven:latest${{ steps.step-variable.outputs.suffix }}
          build-args: |
            REGISTRY_REPO=${{ secrets.DOCKER_USERNAME }}
            RUNTIME=${{ steps.step-variable.outputs.runtime }}
            JAVA_VERSION=${{ matrix.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  e2e:
    runs-on: ubuntu-latest
    if: github.ref_type != 'tag'
    needs: [ init-variable, build-jenkins ]
    steps:  
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Create kind cluster
        uses: helm/kind-action@v1.7.0

      - name: Deploy Chart
        run: |
          ./hack/install/envsubst.sh
          VERSION=${{ needs.init-variable.outputs.container_tag }} make deploy

  publish-chart:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ build-jenkins, build-agent-maven, build-agent-go, build-agent-python, build-agent-nodejs ]
    permissions:
      contents: write
    env:
      HELM_CHARTS_DIR: charts
      HELM_CHART_NAME: jenkins
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Install yq
        uses: chrisdickinson/setup-yq@latest
      - name: Get the version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Tag helm chart image
        run: |
          image_tag=${{ steps.get_version.outputs.VERSION }}
          chart_version=${{ steps.get_version.outputs.VERSION }}
          sed -i "s/latest/${image_tag}/g" $HELM_CHARTS_DIR/values.yaml
          
          # update relok8s_images by language versions matrix.
          echo "updating relok8s_images ...."
          ./hack/update_relok8s_images.sh $HELM_CHARTS_DIR/values.yaml $HELM_CHARTS_DIR/.relok8s-images.yaml
          sed -i "s/latest/${image_tag}/g" $HELM_CHARTS_DIR/.relok8s-images.yaml
          cat $HELM_CHARTS_DIR/.relok8s-images.yaml
          
          chart_smever=${chart_version#"v"}
          sed -i "s/0.1.0/${chart_smever}/g" $HELM_CHARTS_DIR/Chart.yaml

      - uses: getsentry/action-github-app-token@v2
        id: get_app_token
        with:
            app_id: ${{ secrets.APP_ID }}
            private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Sync Chart Repo
        run: |
          git config --global user.email "amamba[bot]@users.noreply.github.com"
          git config --global user.name "amamba[bot]"
          git clone https://x-access-token:${{ steps.get_app_token.outputs.token }}@github.com/amamba-io/charts.git amamba-charts
          helm package $HELM_CHARTS_DIR --destination ./amamba-charts/docs/
          helm repo index --url https://amamba-io.github.io/charts ./amamba-charts/docs/
          cd amamba-charts/
          git add docs/
          chart_version=${{ steps.get_version.outputs.VERSION }}
          git commit -m "update jenkins chart ${chart_version}"
          git push https://x-access-token:${{ steps.get_app_token.outputs.token }}@github.com/amamba-io/charts.git