name: E2E
on:
  pull_request_target:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:  
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Create kind cluster
        uses: helm/kind-action@v1.7.0

      - name: Run chart-testing (install)
        run: helm install jenkins ./charts -n jenkins -f config/e2e.yaml